### ISSUE TITLE
pip3 install errored out

### ISSUE THREAD

**Issue by joeribelis** [initialcommit-com/git-sim#32]
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp7na_a560 get_requires_for_build_wheel /tmp/tmp06pru30b
       cwd: /tmp/pip-install-yv59yffo/manimpango
  Complete output (28 lines):
  Package pangocairo was not found in the pkg-config search path.
  Perhaps you should add the directory containing `pangocairo.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'pangocairo' found
  Traceback (most recent call last):
    File "<string>", line 136, in check_min_version
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version', '1.30.0', 'pangocairo']' returned non-zero exit status 1.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/tmp7na_a560", line 280, in <module>
      main()
    File "/tmp/tmp7na_a560", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp7na_a560", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-p_yhp0a9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-p_yhp0a9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-p_yhp0a9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 203, in <module>
    File "<string>", line 139, in check_min_version
  __main__.RequiredDependencyException: pangocairo >= 1.30.0 is required
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmp7na_a560 get_requires_for_build_wheel /tmp/tmp06pru30b Check the logs for full command output.
administrator@Koper:~$

**Comment by initialcommit-io** [comment]
@joeribelis It's hard to tell without knowing what installation steps you tried, and without even knowing when you're getting that message (during installation or trying to run git-sim).

So for starters I'd recommend making sure you "**Installed Manim and Manim dependencies for your OS**", as mentioned in step (1) of the [quickstart guide](https://github.com/initialcommit-com/git-sim#quickstart).  If you already did that and are still having this issue, please let me know:

-When you're getting that error, is it during install or when trying to run git-sim?
-Exactly what installation steps you went through
-Your OS and OS version

**Comment by paketb0te** [comment]
` main.RequiredDependencyException: pangocairo >= 1.30.0 is required` looks to me like you did not install Manim correctly / followed their installation guide at https://docs.manim.community/en/stable/installation.html

**Comment by initialcommit-io** [comment]
@joeribelis Closing for since we haven't heard back and seems like an installation issue.  Please reopen if any questions or if you still can't get it working.
