### ISSUE TITLE
Win10 -> not find ffmpeg

### ISSUE THREAD

**Issue by Devirob** [initialcommit-com/git-sim#36]
---
Try using git-sim (great idea btw ;) on Windows 10 with Python 3.11 and get:

```
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Manim Community v0.17.2

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\git-sim.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\git_sim\__main__.py", line 248, in main
    scene = gs.GitSim(args)
            ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\git_sim\git_sim.py", line 20, in __init__
    super().__init__()
  File "C:\Python311\Lib\site-packages\manim\scene\moving_camera_scene.py", line 92, in __init__
    super().__init__(camera_class=camera_class, **kwargs)
  File "C:\Python311\Lib\site-packages\manim\scene\scene.py", line 141, in __init__
    self.renderer.init_scene(self)
  File "C:\Python311\Lib\site-packages\manim\renderer\cairo_renderer.py", line 49, in init_scene
    self.file_writer: Any = self._file_writer_class(
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\manim\scene\scene_file_writer.py", line 88, in __init__
    raise RuntimeError(
RuntimeError: Manim could not find ffmpeg, which is required for generating video output.
For installing ffmpeg please consult https://docs.manim.community/en/stable/installation.html
Make sure to either add ffmpeg to the PATH environment variable
or set path to the ffmpeg executable under the ffmpeg header in Manim's configuration.
```
------

I think it is easy to fix by myself - but maybe if you want to share your project you should know about it.

**Comment by initialcommit-io** [comment]
Hi @Devirob - can you let me know the exact installation steps you tried?

Seems like you didn't follow the instructions for [installing Manim and Manim dependencies on your OS](https://github.com/initialcommit-com/git-sim#quickstart).  That will involve installing ffmpeg.  Please follow these steps and let me know if it works for you:

https://docs.manim.community/en/stable/installation/windows.html

**Comment by Devirob** [comment]
What a quick response! Wow! 

You're right - I missed the Manim installation - I've fixed it and now it works.

**Thank you so much.**
